# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: TerraformScan
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        curl -s -G https://shiftleft-prod.s3.amazonaws.com/blades/shiftleft/bin/linux/amd64/0.0.29/shiftleft -o shiftleft
        chmod +x shiftleft
    displayName: 'Install ShiftLeft'
  - task: CmdLine@2
    env:
      CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
      CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
    inputs:
      script: |
        git clone https://github.com/dasalebr/demo.git
        ./shiftleft -D iac-assessment -p ./terraform-template -r -64 -s medium -e 3a99f75d-057f-4f6e-8164-baa9bd0c4d8c
    displayName: 'Terraform - Code Scan'
